[package]
name = "danaustralia/berlin-marathon"
version = "0.1.56"
description = "Berlin Marathon — Data Highlights (static site)"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "public"
